[package]
name = "clinkz-auth"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
uuid = { workspace = true, features = ["v7"]}
axum.workspace = true
sqlx.workspace = true
redis.workspace = true
deadpool-redis.workspace = true
